### ISSUE TITLE
make default print method for zoltr objects more user-friendly

### ISSUE THREAD

**Issue by nickreich** [reichlab/zoltr#7]
As an example, I see this:
```
> the_projects <- projects(conn)
> lapply(the_projects, function(project) {c(project$url, name(project))})
> cond <- sapply(the_projects, function(project) name(project) == "CDC Flu challenge")
> project <- if (any(cond)) the_projects[cond][[1]] else NULL
> project
<environment: 0x7fc429f83a48>
attr(,"class")
[1] "Project"        "ZoltarResource"
```
which tells me nothing about which project it is, which it seems like should be a bare minimum.

**Comment by matthewcornell** [comment]
as discussed with @nickreich on 4/16, I will rewrite the package to mostly use functions to interact with the API rather than via objects. we will pass strings in to functions instead of objects: project_name, model_name, timezero, etc. we will use data frames instead of lists for accessing "compound" items like projects, models, and forecasts.

**Comment by matthewcornell** [comment]
Closed!
